#!/bin/bash

cat << "EOF"

NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM$$VVIFFFFFFFFFFFFFFFFFFIIV$$$MNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM$VIF************FFFF****************FVV$MMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNM$VIF**************************************FFFFFFV$MNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNM$VFFFFFF****************************************F***FFFIV$MNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNMVI*********************************************************FFFIV$MNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNM$IFF*************************************************************FFFIVMNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNM$VFFFFF****************************************************************FFFI$MNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNM$FFF*F***FF*************************************************************FFFFFFFVMNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNMVFFFFF**FFFFFFFFF***VI*********************************FIVVVF**************F*****FFI$NNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNMVF***********FFFFF****$VVIF***************************FFIIVVI**************************I$NNNNNNNNNNNNNNN
NNNNNNNNNNNNNN$F*************FFFFF****FVF****F******FFFIFFIVIF***********FIF*****************************VMNNNNNNNNNNNNN
NNNNNNNNNNNNMI******************FF*****I**::::*********************:::::*F*I*******************************$NNNNNNNNNNNN
NNNNNNNNNNNV****************************F*:::::::****************:::::::**IF********************************FMNNNNNNNNNN
NNNNNNNNNMV********FFFVVVIIIF************I::::::***************:::::::***FVV*********************************F$NNNNNNNNN
NNNNNNNN$F******IVVVVVIFFIV$$$VIFFIVVVIVV$VIFFFFFFFF*F*FIIIFIIIIVVV$$$$$$$$$F***********F****F*****************VNNNNNNNN
NNNNNNN$F****FV$$VFF********IVV$$$VVVVIIV$$$F:************::*V$$$$$$$$$$$$VVI**********IVI***F******************VMNNNNNN
NNNNNN$*****V$$VF**************IVV$$$VIV$V$I.:FF*:***:*F**...F$$$$$$$VVVVV$$$F********I$VF$$V********************INNNNNN
NNNNN$****F$$$I*************IV$VVIFF***FV$$V*:::::**:.:::::::I$$$$$$$VVIFFF***F*******$*.:$V**********************VNNNNN
NNNN$*****V$$V***********FV$$I*******F:::**FFIIIVVVIIIVVVVVVVIFF**************I******V$II$V************************VNNNN
NNNM******$$$V**********I$$$F********F******::....:::::**:::**::::***********:F*****VI:*$V**********F***F***********$NNN
NNNV*****F$$$$F*********$$$$********F**:::IV*:.......:::FFFV$*:::::*****:::::**I***V$F*V$F********IV$I*:*I***********MNN
NN$******F$$$$$V********$$$$F******I*****:..:*:......:****F::.:::**:::*********I**F$FF$VF*******I$F**$$F*F***********VNN
NNV******F$$$$$$F*******$$$$F******F***::.....:.....::....*:.....::*****::::::*I**$*.*$F******FV$V:*I$V***************MN
NMIIFFFF*I$$VF*********I$$$I********I*::::::::.:***:..::::::::......::*********F*V$VV$F******VV**$$$VF****************VN
NVFFFFF***************V$$I************..::::::::::.:::::::::::.:::.....:******IFV$**$V*****I$$F*V$VF*******************M
MF******************F$$VF**************:.:::::::::::.:::::....:.........*FIVV$$VVVVV$VF**FVF*F$$VF*********************$
$*****IIVF********IV$$V*****************::..:...::..:.:...:.........:*I$$$$$$$$$$$$$$$$$V$V**VVF******************FFFFFV
V*****VV$VF*****FV$$$I*******************F::.....................:FV$$$$$$$$$$$VVVVVVIF*FF$$$IFFFF***************FFFFFFV
V******FFFFV$VVV$$$V*****************FIIV$$VI*::::::....::::::*F$$$$$$$$$$$$$VV$$$I****:::*VFFF***************FF*******F
I************FFF*********************$$$IIIV$V:..::::::::..:*V$$$$$$$$$$$$$VVVVVV**::::::::*IFF*************F**********F
I*************************************V$$$$VVVVIIF*:::::*FV$$$$VVVV$$$$VF********FF*::::::::*IF************************F
V**************************************II$$$$VIVVVVVFFV$$$$$$$IV$$$$$I*****:I***:***F*:::::**FI**FF*****FF*************I
V*************************************I**F$$$$$$$$$$$$$$$$$$VVV$$$$$I*:***FIFFFFF****F:*******FIFFF****FF**************I
$*************************************I**FV$$$$$$$$$VVVVVVVVV$$$$$FI******:F$$V*******F********IFFF**FFFFFF************V
MF************************************F**FVVVV$VVVVV$$$$$$$$$$$I*::*******************F*********IF*FFFFFFFFFFFFFF******$
NV***********************************I****FVVVV**V$$$$$$$VF*::...:F*******************F*********IIIIFFFFFFFFFFFFFF**F*IM
NM***********************************I****FVI$$V..::***::........*****************F*FFIF*****:::FVIIIIFFIIIIFFFFFF*F**$N
NNI*****************************FFFF*I*****VIV$$I:*:....*........*********************FF::::::***VVIIIIIIIIIIIFFFFIIFIMN
NNM*************************FFFFFFFF*I****FIII$$$V*:..:..***:..*F*********************I*:********FVVVVVIIIIIIIIIIIIFF$NN
NNN$************F***F**FFFFFFFFFFFFFII*FFF*FV*F$$$V*:*:.....:::******FFF**************II**********VVVVVIIIIIIIIIIIIIVNNN
NNNNVF*********F*********F*FFFFFFFFFFF*****FI**F$V$$V*:..:*...******************FFFFFFFVF*********IVVVIIIVVVVVVVV$$$MNNN
NNNNMI********FF*:**I****FFFIIIIIIFFFI******IF**VV$$$VV***:...*************************I**********IVVV$$$$$$$$$$$$$MNNNN
NNNNNMIF***FFFFF*****I*:*IIIIIIIIIIFFI******FI*****$$V$$$IF*.:************************FI*:****::***$$$$$$$$$$$$$$$MNNNNN
NNNNNNMF**FFFFFF*:**V****IIIIIIIIIIIIFI*****FI**:***VV$$$V$$$IIF**********************IF*:::::::**FV$$$$$$$$$$$$$MNNNNNN
NNNNNNN$FFFFFFIF****V:::*IIIIIIIIIIIIIIVI*F***::::**::*$$V$$$$$$$V********************I*:::**FIV$$$V$$$$$$$$$$$$MNNNNNNN
NNNNNNNNMVFFFIIF*:::*:::*IIIIIIVIVVVVVVI::*******::*:.:***I$$$$$$I*FFIIF*********FFIV$VVVV$$$$$$$$VV$$$$$$$$$$$MNNNNNNNN
NNNNNNNNNM$IIIIF**F******IIIIIIVVVVVVVV**:FF***::*****:::..:*I$$$V***:****FFFFFFFV$$$$$$$$$$$$$VVV$$$$$$$VV$$$MNNNNNNNNN
NNNNNNNNNNNMVIIF*:::::*F*IIIIVVVVVVVVVI****F:*****::***:.......::F:::************V$$$$$$$$$$$$VV$$$$$$$$$$$$MNNNNNNNNNNN
NNNNNNNNNNNNN$VF******IF*IIIIVVV$VVV$VV****FF****::::::**:.......*::***:*********V$$$$$$$VVVVVVIVV$$$$$$$$$MNNNNNNNNNNNN
NNNNNNNNNNNNNNMI*****:***IIIVVV$VVVV$$V*****F::.....::***I**:...:*:::....:::***FVIFFFF***::::***F$$$$$$$$MNNNNNNNNNNNNNN
NNNNNNNNNNNNNNN$I*******FVVVV$$$VVV$$$$F***:**..::::::***I*..::*::::::::::::***I*::::::::::****FV$$$$$$MNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNMM$VVVVVVV$$$$$$$V$$$$$VF***:*::....:::**FF::::..........::***FI*::::********FFV$$M$$MNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNN$:..::...*$V$$VVVV$$$$$$$VIF****...:::::**FV***..........:::**FIF*:************V$$$MMNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNI.:****:.*$$$VVVV$$$$$$$$$$F***F*:::..::***VFF*:::::::::::***FVF*:::::*::*****V$$MMNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNI.******:*MM$V$V$$$$$$$$$$$$I***F..::::***FVVI*.......:::***FVF*::::*******FFIMMNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNV.::**::.*MNNM$$$$$$$$$$$$$$$VF*F*:::.::***VVV::::::::::***IVF**********FFFI$MNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNMF*******VNNNNNNMM$$$$$$$$$$$$VII*::::::***V$*...::::::***IVIF*********FFFIMNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMM$$$MMM$VV*....::***V$*:::..:::***VIII*******FFIIV$MNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMM$$*::::*****V*:::::::****VVIVF**FFFFFVVV$MNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$::...::**F*.....:::***VVVVVIIIIFFV$$MMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
EOF
